### PR TITLE
watt-hours

### PR DESCRIPTION
**Pull request by geofrancis**

### CODE REVIEW

**Comment by RobTillaart** [comment]
Joule is indeed watt-second.and I understand the need for displaying it as watt-hour.

I propose to make a wrapper function in the ina228.h file. 
```cpp
Double getEnergy_Wh()  ....
```
Maybe add  kilo and mega joule wrappers too.

**Comment by RobTillaart** [comment]
Maybe the names should be shorter leading to the following wrappers

```cpp
double getJoule() { return getEnergy(); };
double getKiloJoule() { return getEnergy() * 1e-3; };
double getMegaJoule() { return getEnergy() * 1e-6; };

double getWattSecond() { return getEnergy(); };
double getWattHour() { return getEnergy() * (1.0 / 3600.0); };
double getKiloWattHour() { return getEnergy() * (1.0 / 3.6); };
```

The ordering in the .h file and the readme.md file should be redone.
 so all Vbus are grouped all Vshunt are grouped ... and all Energy are grouped.

**Comment by RobTillaart** [comment]
I will create a PR for the new naming of the wrappers asap => 0.1.4

**Comment by RobTillaart** [comment]
PR for 0.1.4 created,

**Comment by RobTillaart** [comment]
Merged the 0.1.4 version, 
That makes this PR slightly obsolete, or you can redo your patch with the new 0.1.4 interface names?
R.

**Comment by geofrancis** [comment]
just close this if its taken care of

**Comment by RobTillaart** [comment]
If other issues pop up, please let me know!

**Pull request closed without merging**
